### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bururabit** [bururabit/mameya#1]
- [ ] `generate`
  - [ ] Copy asset files on `/path/to/public/`
  - [ ] Get list of Markdown files
  - [ ] Convert Markdown to HTML
  - [ ] Copy to page and post files
- [ ] `new`
  - [ ] `blog`
  - [ ] `page`
  - [ ] `post`
- [ ] `server`
  - Start web server on `/path/to/source/`
